version: "3.9"

services:
  gateway: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    image: gateway
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      GATEWAY_HOST: 0.0.0.0
      GATEWAY_DB_HOST: gateway-db
      GATEWAY_DB_PORT: 5432
      GATEWAY_DB_USER: gateway
      GATEWAY_DB_PASS: gateway
      GATEWAY_DB_BASE: gateway
